# Generated by Django 4.2.1 on 2023-05-26 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_estudios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fecha_nacimiento',
            new_name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='curso',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
