# Generated by Django 4.2.1 on 2023-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0002_rename_fecha_nacimiento_entregable_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('cuerpo', models.CharField(max_length=4000)),
                ('categoria', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias')),
            ],
        ),
    ]
