# Generated by Django 4.2.1 on 2023-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0003_noticias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
    ]
