# Generated by Django 4.2.1 on 2023-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0004_alter_noticias_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fecha_publicacion',
            field=models.DateField(default='2023-05-27'),
            preserve_default=False,
        ),
    ]
