# Generated by Django 4.2.1 on 2023-05-28 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0005_noticias_fecha_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='creador',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 14, 19, 53, 375436)),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
